import canonicalLaneMathlib.AdmissibleClass
import CrystallographyChemistryStructureRefinementCanonicalLaneLean.SpaceGroupClassification
import CrystallographyChemistryStructureRefinementCanonicalLaneLean.XRayDiffraction
import CrystallographyChemistryStructureRefinementCanonicalLaneLean.StructureRefinement
import CrystallographyChemistryStructureRefinementCanonicalLaneLean.QuasicrystalOrder
import CrystallographyChemistryStructureRefinementCanonicalLaneLean.BondValenceSum

namespace HautevilleHouse
namespace CrystallographyChemistryStructureRefinementCanonicalLaneLean

def ConstrainedCrystallographyClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_crystallography_endgame (A : AdmissibleClass) :
    ConstrainedCrystallographyClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end CrystallographyChemistryStructureRefinementCanonicalLaneLean
end HautevilleHouse
